# Generated by Django 4.0.1 on 2022-01-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garyshop', '0004_basket_product_image_product_price_order_basketitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garyshop.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garyshop.product'),
        ),
    ]
